### ISSUE TITLE
Chatbox Mobioos Forge studio : Authentication service unavailable

### ISSUE THREAD

**Issue by LoicGolvan** [Mobioos/Forge-Documentation#1]
Hello,
I've been stuck at the end of the tutorial ("getting started") when you must connect to the chatbot.
I have successfully created an account on https://forge-app.mobioos.ai/ but when I try to connect to the chatbot, I get this message:

"Authentication service unavailable"

I thank you all for the information you can provide.

<img width="288" alt="Service unavailable mobioos" src="https://user-images.githubusercontent.com/52067766/59910496-518c9280-9412-11e9-90d2-51cac6ef9c8c.png">

**Comment by faroukaouini** [comment]
Hi Loic,
You have to enter the "SAAS base address" in order to load the generators from the Mobioos Store.
In the Tools/Options menu, in the "Mobioos Options" node, fill the "SAAS base address" property with the following value : **-app.mobioos.ai**

![image](https://user-images.githubusercontent.com/46433354/59914015-bc8d9780-9419-11e9-852a-cfb1f787af84.png)

**Comment by LoicGolvan** [comment]
Thanks.
